<?php

/**
 * @file
 * Contain theme hook for template.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_theme().
 */
function album_theme($existing, $type, $theme, $path) {

  return [
    'photos_template' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function album_cron() {
  $cid = 'album_id:1';
  Cache::invalidateTags([$cid]);
}

/**
 * Implements hook_block_alter().
 */
function album_block_alter(&$definitions) {
  $definitions['user_login_block']['admin_label'] = t('Login');
}

/**
 * Implements hook_block_build_alter().
 */
function hook_block_build_alter(array &$build, BlockPluginInterface $block) {
  // Add the 'url' cache the block per URL.
  if ($block->getBaseId() == 'myblock') {
    $build['#contexts'][] = 'url';
  }
}

/**
 * Implements hook_block_view_alter().
 */
function hook_block_view_alter(array &$build, BlockPluginInterface $block) {
  // Remove the contextual links on all blocks that provide them.
  if (isset($build['#contextual_links'])) {
    unset($build['#contextual_links']);
  }
}
